FROM python:3.8-alpine3.12 as wheeler
ENV PYTHONUNBUFFERED=1

RUN apk update && \
	apk add --no-cache \
		libpng-dev \
		freetype-dev \
		build-base \
		git \
		postgresql-dev \
		openblas-dev \
		libjpeg-turbo-dev \
		hdf5-dev && \
	rm -rf /var/cache/apk/* && \
	ln -s /usr/include/locale.h /usr/include/xlocale.h

ARG NES_TAG=unset
ARG NES_BRANCH=unset
ARG NES_DIR=/nes
ENV NES_DIR=$NES_DIR

RUN mkdir -p "$NES_DIR"  && \
		# clone a NES release
		if [ "$NES_TAG" != "unset" ]; then \
			echo Cloning tag "$NES_TAG" ;\
			wget https://github.com/neuromat/nes/archive/TAG-"${NES_TAG}".tar.gz -qO - | \
				tar xzv --strip-components=1 -C "$NES_DIR" ;\
			sed -i 's/\(psycopg2==\)[0-9.]\+/\12.7.5/' /nes/patientregistrationsystem/qdc/requirements.txt ;\
			sed -i '1isetuptools>=40.6.3' /nes/patientregistrationsystem/qdc/requirements.txt ;\
			sed -i '1ipip>=18.1' /nes/patientregistrationsystem/qdc/requirements.txt ;\
			echo 'mne>=0.17.0' >> /nes/patientregistrationsystem/qdc/requirements.txt ;\
			echo '-e "git+https://github.com/AllenInstitute/nwb-api.git#egg=nwb&subdirectory=ainwb"' >> /nes/patientregistrationsystem/qdc/requirements.txt ;\
		elif [ "$NES_BRANCH" != "unset" ]; then \
			echo Cloning "$NES_BRANCH" branch ;\
			git clone -j $(nproc) -b "$NES_BRANCH"  https://github.com/neuromat/nes.git "$NES_DIR" ;\
		else \
			echo Cloning master branch ;\
			git clone -j $(nproc) https://github.com/neuromat/nes.git "$NES_DIR" ;\
		fi

RUN mkdir -p /wheels/requirement && \
	cp "$NES_DIR"/patientregistrationsystem/qdc/requirements.txt /wheels/requirement

WORKDIR /wheels

# BEGIN

# Problem: SciPy -> Numpy build fails
# RUN pip3 install -U pip setuptools wheel
#
# Solution: downgrade setuptools to <59.0.0
#	pip and wheel can be upgraded
# [TODO] lock pip and wheel versions to avoid future crashes
RUN pip3 install -U pip wheel
RUN pip3 install "setuptools<59.0.0"

# Problem: build h5py fails. Cargo missing
# Solution: install and add cargo to PATH
# [TODO] lock h5py to current latest
RUN apk add curl
RUN curl -S https://sh.rustup.rs | sh -s -- -y
ENV PATH $HOME/.cargo/bin:$PATH

# END

RUN pip3 install -r requirement/requirements.txt && \
	pip3 wheel -r requirement/requirements.txt
